/**
 * @file matlab_phase_diagram.hpp
 * @brief 相图和 flash 结果的 MATLAB 绘图脚本生成器。
 */
#pragma once

#include <tools/phase_diagram.hpp>

#include <array>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <string_view>

namespace MPMC::tools
{

namespace detail
{

inline std::string matlabQuote(std::string_view text)
{
    std::string result;
    result.reserve(text.size() + 4);
    for (const char ch : text)
    {
        result.push_back(ch);
        if (ch == '\'')
            result.push_back('\'');
    }
    return result;
}

inline void writeMatlabPreamble(std::ostream &out, std::string_view csvFile)
{
    out << "% Auto-generated by MPMC_SCW tools.\n"
        << "% phase_code: 0=failed, 1=O, 2=G, 3=O+G, 4=W, 5=O+W, 6=G+W, 7=O+G+W.\n"
        << "clear; clc;\n"
        << "data = readtable('" << matlabQuote(csvFile) << "');\n"
        << "phaseNames = {'failed','O','G','O+G','W','O+W','G+W','O+G+W'};\n"
        << "phaseColors = lines(8);\n"
        << "if any(ismember(data.Properties.VariableNames, {'phase_code'}))\n"
        << "    valid = data.phase_code > 0;\n"
        << "    if any(~valid)\n"
        << "        fprintf('Warning: %d phase-diagram samples did not converge.\\n', sum(~valid));\n"
        << "    end\n"
        << "else\n"
        << "    valid = true(height(data),1);\n"
        << "end\n";
}

inline void writePhaseScatterLoop(
    std::ostream &out,
    std::string_view xExpression,
    std::string_view yExpression)
{
    out << "codes = unique(data.phase_code(valid));\n"
        << "for ii = 1:numel(codes)\n"
        << "    code = codes(ii);\n"
        << "    mask = data.phase_code == code;\n"
        << "    scatter(" << xExpression << "(mask), " << yExpression
        << "(mask), 20, phaseColors(code+1,:), 'filled', ...\n"
        << "        'DisplayName', phaseNames{code+1});\n"
        << "end\n";
}

inline void createMatlabFile(const std::filesystem::path &path, std::ofstream &out)
{
    if (path.has_parent_path())
        std::filesystem::create_directories(path.parent_path());
    out.open(path);
    if (!out)
        throw std::runtime_error("Cannot create MATLAB phase-diagram script: " + path.string());
}

} // namespace detail

/** @brief 生成 P-T 相区图的 MATLAB 代码。 */
inline void writePressureTemperatureMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view figureTitle = "P-T phase map")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "figure('Color','w'); hold on;\n";
    detail::writePhaseScatterLoop(out, "data.temperature_K", "data.pressure_bar");
    out << "nT = max(data.temperature_index)+1; nP = max(data.pressure_index)+1;\n"
        << "phaseCountGrid = nan(nP,nT);\n"
        << "for rr = 1:height(data)\n"
        << "    phaseCountGrid(data.pressure_index(rr)+1,data.temperature_index(rr)+1) = data.phase_count(rr);\n"
        << "end\n"
        << "Tgrid = sort(unique(data.temperature_K)); Pgrid = sort(unique(data.pressure_bar));\n"
        << "if any(phaseCountGrid(:) > 1)\n"
        << "    contour(Tgrid,Pgrid,phaseCountGrid,[1.5 2.5],'k-','LineWidth',1.1,'HandleVisibility','off');\n"
        << "end\n"
        << "xlabel('Temperature (K)'); ylabel('Pressure (bar)');\n"
        << "title('" << detail::matlabQuote(figureTitle) << "');\n"
        << "legend('Location','best'); grid on; box on;\n"
        << "set(gca,'Layer','top');\n";
}

/** @brief 生成压力-组成相图的 MATLAB 代码。 */
inline void writePressureCompositionMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view pathLabel = "composition path fraction",
    std::string_view figureTitle = "P-composition phase map")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "figure('Color','w'); hold on;\n";
    detail::writePhaseScatterLoop(out, "data.path_fraction", "data.pressure_bar");
    out << "nX = max(data.path_index)+1; nP = max(data.pressure_index)+1;\n"
        << "phaseCountGrid = nan(nP,nX);\n"
        << "for rr = 1:height(data)\n"
        << "    phaseCountGrid(data.pressure_index(rr)+1,data.path_index(rr)+1) = data.phase_count(rr);\n"
        << "end\n"
        << "Xgrid = sort(unique(data.path_fraction)); Pgrid = sort(unique(data.pressure_bar));\n"
        << "if any(phaseCountGrid(:) > 1)\n"
        << "    contour(Xgrid,Pgrid,phaseCountGrid,[1.5 2.5],'k-','LineWidth',1.1,'HandleVisibility','off');\n"
        << "end\n"
        << "xlabel('" << detail::matlabQuote(pathLabel) << "'); ylabel('Pressure (bar)');\n"
        << "title('" << detail::matlabQuote(figureTitle) << "');\n"
        << "legend('Location','best'); grid on; box on;\n"
        << "set(gca,'Layer','top');\n";
}

/** @brief 生成 P-T 平面泡点/露点包络线的 MATLAB 代码。 */
inline void writePressureTemperatureEnvelopeMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view figureTitle = "P-T bubble/dew envelope",
    bool showWaterCriticalReference = false)
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "figure('Color','w'); hold on;\n"
        << "maskD = data.has_dew > 0;\n"
        << "maskB = data.has_bubble > 0;\n"
        << "if any(maskD), plot(data.temperature_K(maskD), data.dew_pressure_bar(maskD), '-o', 'LineWidth',1.3, 'DisplayName','dew line'); end\n"
        << "if any(maskB), plot(data.temperature_K(maskB), data.bubble_pressure_bar(maskB), '-s', 'LineWidth',1.3, 'DisplayName','bubble line'); end\n"
        << "maskC = data.critical_point > 0;\n"
        << "if any(maskC), scatter(data.critical_temperature_K(maskC), data.critical_pressure_bar(maskC), 55, 'filled', 'DisplayName','critical estimate'); end\n";
    if (showWaterCriticalReference)
        out << "scatter(" << WaterCriticalReference::temperatureK << ", " << WaterCriticalReference::pressureBar
            << ", 58, 'p', 'filled', 'DisplayName','H2O critical reference');\n";
    out << "xlabel('Temperature (K)'); ylabel('Pressure (bar)');\n"
        << "title('" << detail::matlabQuote(figureTitle) << "');\n"
        << "legend('Location','best'); grid on; box on; set(gca,'Layer','top');\n";
}

/** @brief 生成定温组成路径泡点/露点曲线的 MATLAB 代码。 */
inline void writePressureCompositionEnvelopeMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view pathLabel = "composition path fraction",
    std::string_view figureTitle = "P-composition bubble/dew envelope")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "figure('Color','w'); hold on;\n"
        << "maskD = data.has_dew > 0;\n"
        << "maskB = data.has_bubble > 0;\n"
        << "if any(maskD), plot(data.path_fraction(maskD), data.dew_pressure_bar(maskD), '-o', 'LineWidth',1.3, 'DisplayName','dew line'); end\n"
        << "if any(maskB), plot(data.path_fraction(maskB), data.bubble_pressure_bar(maskB), '-s', 'LineWidth',1.3, 'DisplayName','bubble line'); end\n"
        << "xlabel('" << detail::matlabQuote(pathLabel) << "'); ylabel('Pressure (bar)');\n"
        << "title('" << detail::matlabQuote(figureTitle) << "');\n"
        << "legend('Location','best'); grid on; box on; set(gca,'Layer','top');\n";
}

/** @brief 生成 P-T 平面近似临界轨迹的 MATLAB 代码。 */
inline void writeCriticalLocusMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view figureTitle = "Approximate critical locus",
    bool showWaterCriticalReference = false)
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "figure('Color','w'); hold on;\n"
        << "mask = data.valid > 0;\n"
        << "if any(mask)\n"
        << "    plot(data.critical_temperature_K(mask), data.critical_pressure_bar(mask), '-k', 'LineWidth',1.0, 'HandleVisibility','off');\n"
        << "    scatter(data.critical_temperature_K(mask), data.critical_pressure_bar(mask), 40, data.path_fraction(mask), 'filled', 'DisplayName','critical-locus estimate');\n"
        << "    cb = colorbar; ylabel(cb, 'path fraction');\n"
        << "end\n";
    if (showWaterCriticalReference)
        out << "scatter(" << WaterCriticalReference::temperatureK << ", " << WaterCriticalReference::pressureBar
            << ", 58, 'p', 'filled', 'DisplayName','H2O critical reference');\n";
    out << "xlabel('Temperature (K)'); ylabel('Pressure (bar)');\n"
        << "title('" << detail::matlabQuote(figureTitle) << "');\n"
        << "legend('Location','best'); grid on; box on; set(gca,'Layer','top');\n";
}

/** @brief 生成带气相质量分率等值线的 P-T 相数图。 */
inline void writePressureTemperatureQualityMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view figureTitle = "P-T phase count and gas quality",
    bool showWaterCriticalReference = false)
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "Tgrid = sort(unique(data.temperature_K)); Pgrid = sort(unique(data.pressure_bar));\n"
        << "nT=numel(Tgrid); nP=numel(Pgrid); phaseGrid=nan(nP,nT); betaG=nan(nP,nT);\n"
        << "for rr=1:height(data)\n"
        << "    if data.phase_code(rr)>0\n"
        << "        phaseGrid(data.pressure_index(rr)+1,data.temperature_index(rr)+1)=data.phase_count(rr);\n"
        << "        betaG(data.pressure_index(rr)+1,data.temperature_index(rr)+1)=data.beta_g(rr);\n"
        << "    end\n"
        << "end\n"
        << "figure('Color','w');\n"
        << "imagesc(Tgrid,Pgrid,phaseGrid); set(gca,'YDir','normal'); hold on;\n"
        << "cb=colorbar; ylabel(cb,'number of active phases');\n"
        << "levels=0.1:0.1:0.9; [C,h]=contour(Tgrid,Pgrid,betaG,levels,'k-','LineWidth',0.8); clabel(C,h,'FontSize',8);\n";
    if (showWaterCriticalReference)
        out << "scatter(" << WaterCriticalReference::temperatureK << ", " << WaterCriticalReference::pressureBar
            << ", 60, 'p', 'filled', 'DisplayName','H2O critical reference');\n";
    out << "xlabel('Temperature (K)'); ylabel('Pressure (bar)');\n"
        << "title('" << detail::matlabQuote(figureTitle) << "'); grid on; box on;\n"
        << "legend('Location','best'); set(gca,'Layer','top');\n";
}

/** @brief 生成压力扫描的通用 flash 结果面板。 */
template <std::size_t N, class Name>
inline void writePressureFlashProfileMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    const std::array<Name, N> &componentNames,
    std::string_view figureTitle = "Flash results versus pressure")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "x=data.pressure_bar; figure('Color','w'); t=tiledlayout(3,2,'TileSpacing','compact');\n"
        << "nexttile; plot(x,data.beta_o,'-',x,data.beta_g,'-',x,data.beta_w,'-','LineWidth',1.2); ylabel('phase mole fraction'); legend('\\beta_o','\\beta_g','\\beta_w'); grid on;\n"
        << "nexttile; plot(x,data.S_o,'-',x,data.S_g,'-',x,data.S_w,'-','LineWidth',1.2); ylabel('saturation'); legend('S_o','S_g','S_w'); grid on;\n"
        << "nexttile; semilogy(x,max(data.rho_m_o,eps),'-',x,max(data.rho_m_g,eps),'-',x,max(data.rho_m_w,eps),'-','LineWidth',1.2); ylabel('molar density (mol/m^3)'); legend('oil','gas','water'); grid on;\n"
        << "nexttile; plot(x,data.Z_o,'-',x,data.Z_g,'-',x,data.Z_w,'-','LineWidth',1.2); ylabel('Z'); legend('oil','gas','water'); grid on;\n"
        << "nexttile; hold on;\n";
    for (std::size_t c = 0; c < N; ++c)
    {
        const auto name = detail::sanitizeColumnName(componentNames[c]);
        out << "semilogy(x,max(data.Kg_" << name << ",eps),'LineWidth',1.0,'DisplayName','K_g "
            << detail::matlabQuote(componentNames[c]) << "');\n";
    }
    out << "ylabel('K_g=x_g/x_o'); legend('Location','best'); grid on;\n"
        << "nexttile; hold on;\n";
    for (std::size_t c = 0; c < N; ++c)
    {
        const auto name = detail::sanitizeColumnName(componentNames[c]);
        out << "plot(x,data.xo_" << name << ",'LineWidth',0.9,'DisplayName','x_o "
            << detail::matlabQuote(componentNames[c]) << "');\n"
            << "plot(x,data.yg_" << name << ",'--','LineWidth',0.9,'DisplayName','y_g "
            << detail::matlabQuote(componentNames[c]) << "');\n"
            << "plot(x,data.xw_" << name << ",':','LineWidth',0.9,'DisplayName','x_w "
            << detail::matlabQuote(componentNames[c]) << "');\n";
    }
    out << "ylabel('phase composition'); xlabel(t,'Pressure (bar)'); legend('Location','eastoutside'); grid on;\n"
        << "title(t,'" << detail::matlabQuote(figureTitle) << "');\n";
}

/** @brief 生成温度扫描的通用 flash 结果面板。 */
template <std::size_t N, class Name>
inline void writeTemperatureFlashProfileMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    const std::array<Name, N> &componentNames,
    std::string_view figureTitle = "Flash results versus temperature")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "x=data.temperature_K; figure('Color','w'); t=tiledlayout(3,2,'TileSpacing','compact');\n"
        << "nexttile; plot(x,data.beta_o,'-',x,data.beta_g,'-',x,data.beta_w,'-','LineWidth',1.2); ylabel('phase mole fraction'); legend('\\beta_o','\\beta_g','\\beta_w'); grid on;\n"
        << "nexttile; plot(x,data.S_o,'-',x,data.S_g,'-',x,data.S_w,'-','LineWidth',1.2); ylabel('saturation'); legend('S_o','S_g','S_w'); grid on;\n"
        << "nexttile; semilogy(x,max(data.rho_m_o,eps),'-',x,max(data.rho_m_g,eps),'-',x,max(data.rho_m_w,eps),'-','LineWidth',1.2); ylabel('molar density (mol/m^3)'); legend('oil','gas','water'); grid on;\n"
        << "nexttile; plot(x,data.Z_o,'-',x,data.Z_g,'-',x,data.Z_w,'-','LineWidth',1.2); ylabel('Z'); legend('oil','gas','water'); grid on;\n"
        << "nexttile; hold on;\n";
    for (std::size_t c = 0; c < N; ++c)
    {
        const auto name = detail::sanitizeColumnName(componentNames[c]);
        out << "semilogy(x,max(data.Kg_" << name << ",eps),'LineWidth',1.0,'DisplayName','K_g "
            << detail::matlabQuote(componentNames[c]) << "');\n";
    }
    out << "ylabel('K_g=x_g/x_o'); legend('Location','best'); grid on;\n"
        << "nexttile; hold on;\n";
    for (std::size_t c = 0; c < N; ++c)
    {
        const auto name = detail::sanitizeColumnName(componentNames[c]);
        out << "plot(x,data.xo_" << name << ",'LineWidth',0.9,'DisplayName','x_o "
            << detail::matlabQuote(componentNames[c]) << "');\n"
            << "plot(x,data.yg_" << name << ",'--','LineWidth',0.9,'DisplayName','y_g "
            << detail::matlabQuote(componentNames[c]) << "');\n"
            << "plot(x,data.xw_" << name << ",':','LineWidth',0.9,'DisplayName','x_w "
            << detail::matlabQuote(componentNames[c]) << "');\n";
    }
    out << "ylabel('phase composition'); xlabel(t,'Temperature (K)'); legend('Location','eastoutside'); grid on;\n"
        << "title(t,'" << detail::matlabQuote(figureTitle) << "');\n";
}

/** @brief 绘制由非限制三相 flash 提取的 O/G/W 相出现边界。 */
inline void writeMultiphaseBoundariesMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    std::string_view figureTitle = "O/G/W phase-onset boundaries")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    out << "% Auto-generated by MPMC_SCW tools.\nclear; clc;\n"
        << "data=readtable('" << detail::matlabQuote(csvFile) << "'); figure('Color','w'); hold on;\n"
        << "names={'oil onset','gas onset','water onset'}; marks={'o','s','^'};\n"
        << "for code=1:3\n"
        << " mask=data.boundary_code==code; if any(mask), plot(data.temperature_K(mask),data.pressure_bar(mask),['-' marks{code}],'LineWidth',1.2,'DisplayName',names{code}); end\n"
        << "end\n"
        << "scatter(" << WaterCriticalReference::temperatureK << "," << WaterCriticalReference::pressureBar
        << ",60,'p','filled','DisplayName','H2O critical reference');\n"
        << "xlabel('Temperature (K)'); ylabel('Pressure (bar)'); title('"
        << detail::matlabQuote(figureTitle) << "'); legend('Location','best'); grid on; box on;\n";
}

/** @brief 叠加多个热力学后端的泡点/露点包络线。 */
template <std::size_t M>
inline void writeBackendEnvelopeComparisonMatlab(
    const std::filesystem::path &scriptPath,
    const std::array<std::string, M> &csvFiles,
    const std::array<std::string, M> &backendNames,
    std::string_view figureTitle = "EOS bubble/dew envelope comparison")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    out << "% Auto-generated by MPMC_SCW tools.\nclear; clc; figure('Color','w'); hold on;\n";
    for (std::size_t i = 0; i < M; ++i)
    {
        out << "d=readtable('" << detail::matlabQuote(csvFiles[i]) << "');\n"
            << "m=d.has_bubble>0; if any(m), plot(d.temperature_K(m),d.bubble_pressure_bar(m),'-','LineWidth',1.3,'DisplayName','"
            << detail::matlabQuote(backendNames[i]) << " bubble'); end\n"
            << "m=d.has_dew>0; if any(m), plot(d.temperature_K(m),d.dew_pressure_bar(m),'--','LineWidth',1.3,'DisplayName','"
            << detail::matlabQuote(backendNames[i]) << " dew'); end\n"
            << "m=d.critical_point>0; if any(m), scatter(d.critical_temperature_K(m),d.critical_pressure_bar(m),48,'filled','DisplayName','"
            << detail::matlabQuote(backendNames[i]) << " critical estimate'); end\n";
    }
    out << "scatter(" << WaterCriticalReference::temperatureK << "," << WaterCriticalReference::pressureBar
        << ",62,'p','filled','DisplayName','H2O critical reference');\n"
        << "xlabel('Temperature (K)'); ylabel('Pressure (bar)'); title('"
        << detail::matlabQuote(figureTitle) << "'); legend('Location','best'); grid on; box on;\n";
}

/** @brief 比较多个热力学后端的近似临界轨迹。 */
template <std::size_t M>
inline void writeCriticalLocusComparisonMatlab(
    const std::filesystem::path &scriptPath,
    const std::array<std::string, M> &csvFiles,
    const std::array<std::string, M> &backendNames,
    std::string_view figureTitle = "EOS critical-locus estimate comparison")
{
    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    out << "% Auto-generated by MPMC_SCW tools.\nclear; clc; figure('Color','w'); t=tiledlayout(1,2,'TileSpacing','compact');\n"
        << "nexttile; hold on;\n";
    for (std::size_t i = 0; i < M; ++i)
        out << "d=readtable('" << detail::matlabQuote(csvFiles[i]) << "'); m=d.valid>0; plot(d.path_fraction(m),d.critical_temperature_K(m),'-o','LineWidth',1.2,'DisplayName','" << detail::matlabQuote(backendNames[i]) << "');\n";
    out << "yline(" << WaterCriticalReference::temperatureK << ",'--','H2O critical T'); xlabel('composition path fraction'); ylabel('critical-estimate T (K)'); grid on; legend('Location','best');\n"
        << "nexttile; hold on;\n";
    for (std::size_t i = 0; i < M; ++i)
        out << "d=readtable('" << detail::matlabQuote(csvFiles[i]) << "'); m=d.valid>0; plot(d.path_fraction(m),d.critical_pressure_bar(m),'-o','LineWidth',1.2,'DisplayName','" << detail::matlabQuote(backendNames[i]) << "');\n";
    out << "yline(" << WaterCriticalReference::pressureBar << ",'--','H2O critical P'); xlabel('composition path fraction'); ylabel('critical-estimate P (bar)'); grid on; legend('Location','best');\n"
        << "title(t,'" << detail::matlabQuote(figureTitle) << "');\n";
}

/**
 * @brief 生成三元相图及可选 O-G tie line 的 MATLAB 代码。
 *
 * The CSV already contains barycentric Cartesian coordinates.  Phase
 * compositions from the production flash are also exported, allowing the
 * generated script to draw representative O-G tie lines without recomputing
 * equilibrium in MATLAB.
 */
template <std::size_t N, class Name>
inline void writeTernaryMatlab(
    const std::filesystem::path &scriptPath,
    std::string_view csvFile,
    const std::array<Name, N> &componentNames,
    std::array<int, 3> components,
    std::string_view figureTitle = "Ternary phase map")
{
    for (int c : components)
        if (c < 0 || c >= static_cast<int>(N))
            throw std::invalid_argument("MATLAB ternary component index is out of range.");

    const auto a = detail::sanitizeColumnName(componentNames[static_cast<std::size_t>(components[0])]);
    const auto b = detail::sanitizeColumnName(componentNames[static_cast<std::size_t>(components[1])]);
    const auto c = detail::sanitizeColumnName(componentNames[static_cast<std::size_t>(components[2])]);

    std::ofstream out;
    detail::createMatlabFile(scriptPath, out);
    detail::writeMatlabPreamble(out, csvFile);
    out << "figure('Color','w'); hold on; axis equal;\n"
        << "plot([0 1 0.5 0], [0 0 sqrt(3)/2 0], 'k-', 'HandleVisibility','off');\n";
    detail::writePhaseScatterLoop(out, "data.ternary_x", "data.ternary_y");

    out << "og = find(data.phase_code == 3);\n"
        << "if ~isempty(og)\n"
        << "    stride = max(1, ceil(numel(og)/20));\n"
        << "    for kk = 1:stride:numel(og)\n"
        << "        r = og(kk);\n"
        << "        xoA = data.xo_" << a << "(r); xoB = data.xo_" << b << "(r); xoC = data.xo_" << c << "(r);\n"
        << "        ygA = data.yg_" << a << "(r); ygB = data.yg_" << b << "(r); ygC = data.yg_" << c << "(r);\n"
        << "        xoSum = xoA + xoB + xoC; ygSum = ygA + ygB + ygC;\n"
        << "        if xoSum > 0 && ygSum > 0\n"
        << "            xoA=xoA/xoSum; xoB=xoB/xoSum; xoC=xoC/xoSum;\n"
        << "            ygA=ygA/ygSum; ygB=ygB/ygSum; ygC=ygC/ygSum;\n"
        << "            plot([xoB+0.5*xoC, ygB+0.5*ygC], ...\n"
        << "                 [sqrt(3)/2*xoC, sqrt(3)/2*ygC], '-', ...\n"
        << "                 'Color',[0.45 0.45 0.45], 'HandleVisibility','off');\n"
        << "        end\n"
        << "    end\n"
        << "end\n"
        << "three = find(data.phase_code == 7, 1, 'first');\n"
        << "if ~isempty(three)\n"
        << "    r = three;\n"
        << "    pA=[data.xo_" << a << "(r),data.xo_" << b << "(r),data.xo_" << c << "(r)];\n"
        << "    pG=[data.yg_" << a << "(r),data.yg_" << b << "(r),data.yg_" << c << "(r)];\n"
        << "    pW=[data.xw_" << a << "(r),data.xw_" << b << "(r),data.xw_" << c << "(r)];\n"
        << "    pA=pA/sum(pA); pG=pG/sum(pG); pW=pW/sum(pW);\n"
        << "    tx=[pA(2)+0.5*pA(3),pG(2)+0.5*pG(3),pW(2)+0.5*pW(3),pA(2)+0.5*pA(3)];\n"
        << "    ty=sqrt(3)/2*[pA(3),pG(3),pW(3),pA(3)];\n"
        << "    plot(tx,ty,'k-','LineWidth',1.3,'HandleVisibility','off');\n"
        << "end\n";

    out << "text(-0.04,-0.035,'" << detail::matlabQuote(componentNames[static_cast<std::size_t>(components[0])]) << "', ...\n"
        << "    'HorizontalAlignment','right');\n"
        << "text(1.04,-0.035,'" << detail::matlabQuote(componentNames[static_cast<std::size_t>(components[1])]) << "');\n"
        << "text(0.5,sqrt(3)/2+0.045,'" << detail::matlabQuote(componentNames[static_cast<std::size_t>(components[2])]) << "', ...\n"
        << "    'HorizontalAlignment','center');\n"
        << "xlim([-0.08 1.08]); ylim([-0.08 sqrt(3)/2+0.08]); axis off;\n"
        << "title('" << detail::matlabQuote(figureTitle) << "');\n"
        << "legend('Location','eastoutside');\n";
}

} // namespace MPMC::tools
