#!/usr/bin/env python3
"""H02 A/B/C conditional-mechanism post-processing and acceptance gate.

No physical calibration is inferred here. The script only combines exact
accepted-step producer ledgers and well histories generated by the simulator.
"""
from __future__ import annotations
import argparse
import csv
import math
from pathlib import Path

PHASES = ("Oil", "Gas", "Water")
SCOPE = "CONDITIONAL_MECHANISM_EXPERIMENT_NOT_REAL_HEAVY_VALIDATION"

def read_csv(path: Path):
    with path.open(newline="") as f:
        return list(csv.DictReader(f))

def num(row, key, default=float("nan")):
    try:
        return float(row[key])
    except (KeyError, TypeError, ValueError):
        return default

def h02_mu(water_mass_fraction: float, mode: str) -> float:
    if not math.isfinite(water_mass_fraction):
        return float("nan")
    w = min(1.0, max(0.0, water_mass_fraction))
    if mode == "A":
        raise ValueError("A viscosity is phase-fixed, not composition mixed")
    if mode == "B":
        if w <= 0.25:
            v = 0.0
        elif w >= 0.75:
            v = 1.0
        else:
            s = (w - 0.25) / 0.5
            v = s * s * (3.0 - 2.0 * s)
    elif mode == "C":
        v = w
    else:
        raise ValueError(mode)
    return math.exp(math.log(2.0e-3) + v * math.log(5.0e-5 / 2.0e-3))

def phase_mu(row, phase: str, mode: str) -> float:
    if mode == "A":
        return 5.0e-5 if phase == "Water" else 2.0e-3
    wh = num(row, f"m_dot_{phase}_H2O_produced_kg_s", 0.0)
    hh = num(row, f"m_dot_{phase}_OIL_HEAVY_produced_kg_s", 0.0)
    total = wh + hh
    if total <= 1.0e-30:
        return float("nan")
    return h02_mu(wh / total, mode)

def load_mode(root: Path, mode: str):
    prod = read_csv(root / mode / "producer_composition.csv")
    well = read_csv(root / mode / "well_history.csv")
    by_step = {}
    for row in well:
        by_step.setdefault(int(row["step"]), {})[row["name"]] = row
    out = []
    for row in prod:
        step = int(row["step"])
        wells = by_step.get(step, {})
        inj = wells.get("SCW_INJ", {})
        prd = wells.get("PROD", {})
        inj_bhp_bar = num(inj, "bhp")
        prod_bhp_bar = num(prd, "bhp")
        delta_p_mpa = (inj_bhp_bar - prod_bhp_bar) * 0.1
        rec = {
            "scope": SCOPE,
            "mode": mode,
            "step": step,
            "time_s": num(row, "time_s"),
            "pvi": num(row, "pvi"),
            "RF_H": num(row, "RF_OIL_HEAVY"),
            "cum_Heavy_kg": num(row, "cum_OIL_HEAVY_produced_kg"),
            "deltaP_MPa": delta_p_mpa,
            "injector_BHP_MPa": inj_bhp_bar * 0.1,
            "producer_BHP_MPa": prod_bhp_bar * 0.1,
            "injector_control": inj.get("active_control", ""),
        }
        weighted_num = 0.0
        weighted_den = 0.0
        for phase in PHASES:
            rate = num(row, f"m_dot_{phase}_OIL_HEAVY_produced_kg_s", 0.0)
            cum = num(row, f"cum_{phase}_OIL_HEAVY_produced_kg", 0.0)
            mu = phase_mu(row, phase, mode)
            rec[f"m_dot_Heavy_{phase}_kg_s"] = rate
            rec[f"cum_Heavy_{phase}_kg"] = cum
            rec[f"mu_{phase}_Pa_s"] = mu
            if rate > 0.0 and math.isfinite(mu):
                weighted_num += rate * mu
                weighted_den += rate
        rec["mu_Heavy_carrier_Pa_s"] = (
            weighted_num / weighted_den if weighted_den > 0.0 else float("nan")
        )
        out.append(rec)
    return out

def first_at_or_above(rows, target):
    for row in rows:
        if row["pvi"] >= target - 1.0e-12:
            return row
    return rows[-1]

def interpolate(rows, target, key):
    finite = [(r["pvi"], r[key]) for r in rows
              if math.isfinite(r["pvi"]) and math.isfinite(r[key])]
    if not finite:
        return float("nan")
    if target <= finite[0][0]:
        return finite[0][1]
    for (x0, y0), (x1, y1) in zip(finite, finite[1:]):
        if x0 <= target <= x1 and x1 > x0:
            a = (target - x0) / (x1 - x0)
            return y0 + a * (y1 - y0)
    return finite[-1][1]

def write_csv(path: Path, rows):
    if not rows:
        return
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    modes = {m: load_mode(args.root, m) for m in ("A", "B", "C")}
    write_csv(args.out / "h02_mechanism_timeseries.csv",
              [r for m in ("A", "B", "C") for r in modes[m]])

    summary = []
    for target in (1.0, 2.0):
        for mode in ("A", "B", "C"):
            r = first_at_or_above(modes[mode], target)
            summary.append({
                "scope": SCOPE,
                "target_pvi": target,
                "mode": mode,
                "actual_pvi": r["pvi"],
                "time_s": r["time_s"],
                "RF_H": r["RF_H"],
                "cum_Heavy_Oil_kg": r["cum_Heavy_Oil_kg"],
                "cum_Heavy_Gas_kg": r["cum_Heavy_Gas_kg"],
                "cum_Heavy_Water_kg": r["cum_Heavy_Water_kg"],
                "deltaP_MPa": r["deltaP_MPa"],
                "mu_Heavy_carrier_Pa_s": r["mu_Heavy_carrier_Pa_s"],
                "injector_control": r["injector_control"],
            })
    write_csv(args.out / "h02_mechanism_at_1_2_pvi.csv", summary)

    bc = []
    for i in range(0, 101):
        pvi = 0.02 * i
        b = interpolate(modes["B"], pvi, "mu_Heavy_carrier_Pa_s")
        c = interpolate(modes["C"], pvi, "mu_Heavy_carrier_Pa_s")
        bc.append({
            "scope": SCOPE,
            "pvi": pvi,
            "mu_B_Heavy_carrier_Pa_s": b,
            "mu_C_Heavy_carrier_Pa_s": c,
            "delta_mu_C_minus_B_Pa_s": c - b if math.isfinite(b) and math.isfinite(c) else float("nan"),
            "relative_delta_C_minus_B": (c - b) / b if math.isfinite(b) and math.isfinite(c) and b != 0.0 else float("nan"),
        })
    write_csv(args.out / "h02_bc_viscosity_delta.csv", bc)

    failures = []
    for mode, rows in modes.items():
        last = rows[-1]
        if last["pvi"] < 1.99:
            failures.append(f"{mode}: final PVI {last['pvi']:.9g} < 1.99")
        phase_sum = sum(last[f"cum_Heavy_{p}_kg"] for p in PHASES)
        total = last["cum_Heavy_kg"]
        tol = 1.0e-10 * max(1.0, abs(total))
        if abs(phase_sum - total) > tol:
            failures.append(
                f"{mode}: phase Heavy cumulative {phase_sum:.17g} != total {total:.17g}")
    if abs(modes["A"][-1]["cum_Heavy_Water_kg"]) > 1.0e-12:
        failures.append("A: no-transfer baseline produced Heavy through Water phase")

    print("H02_SCOPE=" + SCOPE)
    print((args.out / "h02_mechanism_at_1_2_pvi.csv").read_text())
    if failures:
        print("H02_FULL_CHAIN=FAIL")
        for item in failures:
            print(" - " + item)
        raise SystemExit(2)
    print("H02_FULL_CHAIN=PASS")

if __name__ == "__main__":
    main()
