// Diagnostic continuation of a fixed-root LLV onset and a separate LL spinodal.
// Production EOS/frozen Jia factory are reused; no physical parameter is fitted.
#define main athabasca_reference_entrypoint
#include "../cpa_athabasca_bitumen_water/main.cpp"
#undef main
#include <chrono>
namespace locus {
using Vec=std::array<double,14>;
using Mat=std::array<std::array<double,14>,14>;
using Hess=std::array<std::array<double,4>,4>;
struct State {bool valid=false; Vec r{}; std::array<Composition,3> x{}; std::array<double,3> Z{}; double p=0,b=0,norm=1e100;};
Composition composition(const Vec&u,int k){Composition x{};double m=0,s=0;for(int i=0;i<4;++i)m=std::max(m,u[k+i]);for(int i=0;i<5;++i){x[i]=std::exp((i<4?u[k+i]:0)-m);s+=x[i];}for(double &v:x)v/=s;return x;}
void encode(Vec &u,int k,const Composition &x){for(int i=0;i<4;++i)u[k+i]=std::log(x[i]/x[4]);}
double gap(const Composition&a,const Composition&b){double s=0;for(int i=0;i<5;++i)s+=std::abs(a[i]-b[i]);return s;}
State eval(const Eos&eos,double t,const Composition&z,const Vec&u,bool onset,double fixedP=0){State s;try{s.x[0]=composition(u,0);s.x[1]=composition(u,4);s.x[2]=composition(u,8);s.p=onset?std::exp(u[13]):fixedP;s.b=1/(1+std::exp(-u[12]));if(s.p<1||s.p>45)return s;std::array<Composition,3> mu{};for(int k=0;k<(onset?3:2);++k){auto role=k==2?MPMC::CompositionalPhase::Gas:MPMC::CompositionalPhase::Oil;auto th=eos.phaseResult(s.p*1e6,t,s.x[k],role,false);s.Z[k]=th.compressibility;for(int i=0;i<5;++i)mu[k][i]=std::log(s.x[k][i]*th.fugacityCoefficient[i]);}for(int i=0;i<5;++i){s.r[i]=mu[0][i]-mu[1][i];if(onset)s.r[5+i]=mu[0][i]-mu[2][i];}for(int i=0;i<4;++i)s.r[(onset?10:5)+i]=(s.b*s.x[0][i]+(1-s.b)*s.x[1][i]-z[i]);s.norm=0;for(int i=0;i<(onset?14:9);++i){if(!std::isfinite(s.r[i]))return s;s.norm=std::max(s.norm,std::abs(s.r[i]));}s.valid=true;}catch(const std::exception&){}return s;}
bool linear(Mat a,Vec b,Vec &x,int n){for(int j=0;j<n;++j){int p=j;for(int i=j+1;i<n;++i)if(std::abs(a[i][j])>std::abs(a[p][j]))p=i;if(std::abs(a[p][j])<1e-16)return false;std::swap(a[p],a[j]);std::swap(b[p],b[j]);for(int i=j+1;i<n;++i){double f=a[i][j]/a[j][j];for(int k=j;k<n;++k)a[i][k]-=f*a[j][k];b[i]-=f*b[j];}}for(int j=n-1;j>=0;--j){double s=b[j];for(int i=j+1;i<n;++i)s-=a[j][i]*x[i];x[j]=s/a[j][j];}return true;}
bool correct(const Eos&eos,double t,const Composition&z,Vec &u,bool onset,double p=0){int n=onset?14:9;for(int it=0;it<45;++it){auto s=eval(eos,t,z,u,onset,p);if(!s.valid)return false;if(s.norm<2e-10)return true;Mat a{};Vec rhs{},d{};for(int j=0;j<n;++j){int ix=onset?j:(j==8?12:j);double h=2e-5;Vec up=u,um=u;up[ix]+=h;um[ix]-=h;auto sp=eval(eos,t,z,up,onset,p),sm=eval(eos,t,z,um,onset,p);if(!sp.valid||!sm.valid)return false;for(int i=0;i<n;++i)a[i][j]=(sp.r[i]-sm.r[i])/(2*h);}for(int i=0;i<n;++i)rhs[i]=-s.r[i];if(!linear(a,rhs,d,n))return false;double scale=1;for(int j=0;j<n;++j)scale=std::min(scale,0.7/std::max(0.7,std::abs(d[j])));bool accepted=false;for(int k=0;k<18;++k){Vec v=u;for(int j=0;j<n;++j)v[onset?j:(j==8?12:j)]+=scale*d[j];auto q=eval(eos,t,z,v,onset,p);if(q.valid&&q.norm<s.norm){u=v;accepted=true;break;}scale*=0.5;}if(!accepted)return false;}return false;}
std::array<double,4> muDiff(const Eos&eos,double t,double p,const Composition&x, bool vapor=false){auto th=eos.phaseResult(p*1e6,t,x,vapor?MPMC::CompositionalPhase::Gas:MPMC::CompositionalPhase::Oil,false);std::array<double,4> mu{};for(int i=0;i<4;++i)mu[i]=std::log(x[i]*th.fugacityCoefficient[i]/(x[4]*th.fugacityCoefficient[4]));return mu;}
std::array<double,2> curvature(const Eos&eos,double t,double p,const Composition &x,bool vapor=false,double factor=1e-5){Hess h{};for(int j=0;j<4;++j){double d=factor*std::min(x[j],x[4]);auto xp=x,xm=x;xp[j]+=d;xp[4]-=d;xm[j]-=d;xm[4]+=d;auto mp=muDiff(eos,t,p,xp,vapor),mm=muDiff(eos,t,p,xm,vapor);for(int i=0;i<4;++i)h[i][j]=(mp[i]-mm[i])/(2*d);}double asym=0;for(int i=0;i<4;++i)for(int j=0;j<i;++j){asym=std::max(asym,std::abs(h[i][j]-h[j][i]));h[i][j]=h[j][i]=(h[i][j]+h[j][i])*0.5;}for(int it=0;it<80;++it){int a=0,b=1;for(int i=0;i<4;++i)for(int j=i+1;j<4;++j)if(std::abs(h[i][j])>std::abs(h[a][b])){a=i;b=j;}if(std::abs(h[a][b])<1e-11)break;double theta=0.5*std::atan2(2*h[a][b],h[b][b]-h[a][a]),c=std::cos(theta),s=std::sin(theta);double aa=h[a][a],bb=h[b][b],ab=h[a][b];for(int k=0;k<4;++k)if(k!=a&&k!=b){double ka=h[k][a],kb=h[k][b];h[k][a]=h[a][k]=c*ka-s*kb;h[k][b]=h[b][k]=s*ka+c*kb;}h[a][a]=c*c*aa-2*c*s*ab+s*s*bb;h[b][b]=s*s*aa+2*c*s*ab+c*c*bb;h[a][b]=h[b][a]=0;}double l=h[0][0];for(int i=1;i<4;++i)l=std::min(l,h[i][i]);return {l,asym};}
void writeState(std::ostream&os,const Eos&eos,double t,const Composition&z,const Vec&u,const std::string&dir){auto s=eval(eos,t,z,u,true);auto co=curvature(eos,t,s.p,s.x[0]),cv=curvature(eos,t,s.p,s.x[2],true),half=curvature(eos,t,s.p,s.x[0],false,5e-6);os<<dir<<','<<t<<','<<s.p<<','<<s.b<<','<<s.norm<<','<<gap(s.x[0],s.x[2])<<','<<gap(s.x[1],s.x[2])<<','<<s.Z[0]/s.Z[2]<<','<<co[0]<<','<<cv[0]<<','<<half[0]<<','<<co[1];for(int k=0;k<3;++k){os<<','<<s.Z[k];for(double x:s.x[k])os<<','<<x;}os<<std::endl;}
}
int runLocus(int argc,char**argv){try{if(argc!=2&&argc!=3)throw std::invalid_argument("usage: locus OUTPUT_DIR [STEP_K]"); const double maxStep=argc==3?std::stod(argv[2]):0.5; if(!(maxStep>0&&maxStep<=0.5))throw std::invalid_argument("STEP_K must be in (0,0.5]");std::filesystem::create_directories(argv[1]);const std::filesystem::path out=argv[1];std::ofstream rows(out/"vapor_onset.csv"),spin(out/"oil_spinodal.csv"),failed(out/"continuation_events.csv");rows<<std::setprecision(17)<<"direction,T_K,P_MPa,beta_oil,closure_norm,vapor_oil_L1,vapor_water_L1,vapor_oil_molar_density_ratio,oil_lambda_min,vapor_lambda_min,oil_lambda_half,oil_hessian_asym";for(int k=0;k<3;++k){rows<<",Z_"<<k;for(int i=0;i<5;++i)rows<<",x"<<i<<"_"<<k;}rows<<'\n';spin<<std::setprecision(17)<<"T_K,P_spinodal_MPa,lambda_min,bracket_MPa,residual,lambda_half,oil_xH2O,status\n";failed<<"T_K,step_K,reason\n";
Eos eos=makeJiaCase1Cpa();MPMC::ThreePhaseFlashOptions opts;opts.waterComponent=0;opts.maximumIterations=240;opts.maximumStabilityIterations=160;opts.cpaSelectGibbsMinimumRoot=true;Flash flash(eos,opts);auto z=feedFromWaterMassFraction(.441);const auto ow=MPMC::PhasePresence(static_cast<std::uint8_t>(MPMC::PhasePresence::oilBit|MPMC::PhasePresence::waterBit));double p=30;auto r=flash.flashRestricted(p*1e6,583,z,ow);while(p>10.63521773&&r.converged){p=std::max(10.63521773,p-.1);r=flash.flashRestricted(p*1e6,583,z,ow,r.composition);}if(!r.converged)throw std::runtime_error("583K OW anchor failed");auto st=flash.stabilityTest(p*1e6,583,z,r.presence,r.composition);if(!st.valid)throw std::runtime_error("583K candidate failed");locus::Vec seed{};locus::encode(seed,0,r.composition[0]);locus::encode(seed,4,r.composition[2]);locus::encode(seed,8,st.incipientComposition[1]);seed[12]=std::log(r.phaseMoleFraction[0]/r.phaseMoleFraction[2]);seed[13]=std::log(10.65521773);if(!locus::correct(eos,583,z,seed,true))throw std::runtime_error("onset initial corrector failed");locus::writeState(rows,eos,583,z,seed,"anchor");
auto u=seed;double t=583,dt=maxStep;while(t<620){auto trial=u;double next=std::min(620.,t+dt);bool ok=locus::correct(eos,next,z,trial,true);auto s=locus::eval(eos,next,z,trial,true);if(!ok||locus::gap(s.x[0],s.x[2])<1e-5||std::abs(std::log(s.p)-u[13])>.08){failed<<next<<','<<dt<<",corrector_or_identity_rejected\n";dt*=.5;if(dt<.0005)break;continue;}u=trial;t=next;locus::writeState(rows,eos,t,z,u,"forward");std::cout<<"vapor T="<<t<<" P="<<s.p<<" L1="<<locus::gap(s.x[0],s.x[2])<<std::endl;if(dt<maxStep)dt=std::min(maxStep,dt*1.5);}
// Reverse corrector checks direction dependence of the identified branch.
while(t>583.000001){auto trial=u;double next=std::max(583.,t-.5);if(!locus::correct(eos,next,z,trial,true)){failed<<next<<",-0.5,reverse_failed\n";break;}u=trial;t=next;locus::writeState(rows,eos,t,z,u,"reverse");}
// Independent spinodal search follows the high-pressure LL branch down in P.
for(double ts=583;ts<=615;ts+=1){auto a=seed;double high=25;bool ok=locus::correct(eos,ts,z,a,false,high);if(!ok){spin<<ts<<",nan,nan,nan,nan,nan,nan,ANCHOR_FAIL\n";continue;}auto ss=locus::eval(eos,ts,z,a,false,high);double lh=locus::curvature(eos,ts,high,ss.x[0])[0];bool found=false;for(double low=high-.2;low>=7;low-=.2){auto b=a;if(!locus::correct(eos,ts,z,b,false,low)){spin<<ts<<",nan,nan,nan,nan,nan,nan,LL_CORRECTOR_FAIL\n";found=true;break;}auto sl=locus::eval(eos,ts,z,b,false,low);double ll=locus::curvature(eos,ts,low,sl.x[0])[0];if(lh>0&&ll<=0){double pl=low,ph=high;auto last=b;bool refined=true;for(int j=0;j<25;++j){double pm=.5*(pl+ph);auto m=a;if(!locus::correct(eos,ts,z,m,false,pm)){refined=false;break;}auto sm=locus::eval(eos,ts,z,m,false,pm);double lm=locus::curvature(eos,ts,pm,sm.x[0])[0];last=m;if(lm>0){ph=pm;a=m;}else{pl=pm;b=m;}}double ps=.5*(pl+ph);locus::correct(eos,ts,z,last,false,ps);auto res=locus::eval(eos,ts,z,last,false,ps);spin<<ts<<','<<ps<<','<<locus::curvature(eos,ts,ps,res.x[0])[0]<<','<<ph-pl<<','<<res.norm<<','<<locus::curvature(eos,ts,ps,res.x[0],false,5e-6)[0]<<','<<res.x[0][0]<<','<<(refined?"CURVATURE_ZERO":"REFINEMENT_FAIL")<<std::endl;std::cout<<"spin T="<<ts<<" P="<<ps<<std::endl;found=true;break;}a=b;lh=ll;high=low;}if(!found)spin<<ts<<",nan,nan,nan,nan,nan,nan,NO_ZERO_IN_SCAN\n";}
return 0;}catch(const std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}

#ifndef LOCUS_LIBRARY
int main(int argc,char**argv){return runLocus(argc,argv);}
#endif
