// Refine intersection and explore a turning point by pseudo-arclength.
#define LOCUS_LIBRARY
#include "main.cpp"
namespace refine {
using Q=std::array<double,15>;using A=std::array<std::array<double,15>,15>;
bool linear15(A a,Q b,Q&x){for(int j=0;j<15;++j){int p=j;for(int i=j+1;i<15;++i)if(std::abs(a[i][j])>std::abs(a[p][j]))p=i;if(std::abs(a[p][j])<1e-16)return false;std::swap(a[j],a[p]);std::swap(b[j],b[p]);for(int i=j+1;i<15;++i){double f=a[i][j]/a[j][j];for(int k=j;k<15;++k)a[i][k]-=f*a[j][k];b[i]-=f*b[j];}}for(int j=14;j>=0;--j){double v=b[j];for(int k=j+1;k<15;++k)v-=a[j][k]*x[k];x[j]=v/a[j][j];}return true;}
Q residual(const Eos&eos,const Composition&z,const Q&q,const Q&pred,const Q&tau){locus::Vec u{};std::copy_n(q.begin(),14,u.begin());auto st=locus::eval(eos,q[14],z,u,true);Q r{};for(int i=0;i<14;++i)r[i]=st.valid?st.r[i]:1e30;r[14]=0;for(int i=0;i<15;++i)r[14]+=(q[i]-pred[i])*tau[i];return r;}
double norm(const Q&r){double v=0;for(double a:r)v=std::max(v,std::abs(a));return v;}
bool correctArc(const Eos&eos,const Composition&z,Q&q,const Q&pred,const Q&tau){for(int it=0;it<35;++it){auto r=residual(eos,z,q,pred,tau);if(norm(r)<2e-10)return true;A a{};Q b{},d{};for(int j=0;j<15;++j){double h=j==14?1e-4:2e-5;auto qp=q,qm=q;qp[j]+=h;qm[j]-=h;auto rp=residual(eos,z,qp,pred,tau),rm=residual(eos,z,qm,pred,tau);for(int i=0;i<15;++i)a[i][j]=(rp[i]-rm[i])/(2*h);}for(int i=0;i<15;++i)b[i]=-r[i];if(!linear15(a,b,d))return false;bool accepted=false;for(double scale=1;scale>1e-5;scale*=.5){auto trial=q;for(int i=0;i<15;++i)trial[i]+=scale*d[i];if(norm(residual(eos,z,trial,pred,tau))<norm(r)){q=trial;accepted=true;break;}}if(!accepted)return false;}return false;}
locus::Vec decode(const std::vector<std::string>&r){locus::Vec u{};for(int k=0;k<3;++k){Composition x{};for(int i=0;i<5;++i)x[i]=std::stod(r.at(13+6*k+i));locus::encode(u,k*4,x);}double b=std::stod(r.at(3));u[12]=std::log(b/(1-b));u[13]=std::log(std::stod(r.at(2)));return u;}
}
int main(int argc,char**argv){try{if(argc!=3)throw std::invalid_argument("usage: refine VAPOR_CSV OUTPUT_DIR");std::ifstream in(argv[1]);std::string line;std::getline(in,line);std::vector<std::vector<std::string>> f;while(std::getline(in,line)){auto r=splitCsv(line);if(r[0]!="reverse")f.push_back(r);}if(f.size()<3)throw std::runtime_error("not enough continuation points");std::filesystem::path out=argv[2];std::filesystem::create_directories(out);Eos eos=makeJiaCase1Cpa();auto z=feedFromWaterMassFraction(.441);
// Independent T bracketing of oil curvature along the retained vapor onset.
auto base=refine::decode(f.front());double lo=589,hi=589.5;for(int j=0;j<30;++j){double t=(lo+hi)*.5;auto u=base;if(!locus::correct(eos,t,z,u,true))throw std::runtime_error("intersection corrector failed");auto s=locus::eval(eos,t,z,u,true);if(locus::curvature(eos,t,s.p,s.x[0])[0]>0)lo=t;else hi=t;base=u;}
double tc=(lo+hi)*.5;auto sc=locus::eval(eos,tc,z,base,true);std::ofstream inter(out/"intersection.csv");inter<<std::setprecision(17)<<"T_K,P_MPa,residual,vapor_oil_L1,vapor_oil_molar_density_ratio,oil_lambda,oil_lambda_half,gas_lambda,water_lambda,oil_xH2O,gas_xH2O\n"<<tc<<','<<sc.p<<','<<sc.norm<<','<<locus::gap(sc.x[0],sc.x[2])<<','<<sc.Z[0]/sc.Z[2]<<','<<locus::curvature(eos,tc,sc.p,sc.x[0])[0]<<','<<locus::curvature(eos,tc,sc.p,sc.x[0],false,5e-6)[0]<<','<<locus::curvature(eos,tc,sc.p,sc.x[2],true)[0]<<','<<locus::curvature(eos,tc,sc.p,sc.x[1])[0]<<','<<sc.x[0][0]<<','<<sc.x[2][0]<<'\n';
// Traverse the apparent high-T endpoint without assuming T is monotone.
auto u1=refine::decode(f[f.size()-2]),u2=refine::decode(f.back());refine::Q q1{},q2{};std::copy(u1.begin(),u1.end(),q1.begin());std::copy(u2.begin(),u2.end(),q2.begin());q1[14]=std::stod(f[f.size()-2][1]);q2[14]=std::stod(f.back()[1]);std::ofstream arc(out/"arclength.csv");arc<<std::setprecision(17)<<"index,T_K,P_MPa,residual,vapor_oil_L1,vapor_oil_molar_density_ratio,oil_lambda,gas_lambda,water_lambda,tangent_T,step_arc\n";double ds=.005;for(int k=0;k<180;++k){refine::Q tau{},pred{};double n=0;for(int i=0;i<15;++i){tau[i]=q2[i]-q1[i];n+=tau[i]*tau[i];}n=std::sqrt(n);for(int i=0;i<15;++i){tau[i]/=n;pred[i]=q2[i]+ds*tau[i];}auto q=pred;if(!refine::correctArc(eos,z,q,pred,tau)){ds*=.5;if(ds<1e-6)break;--k;continue;}locus::Vec u{};std::copy_n(q.begin(),14,u.begin());auto s=locus::eval(eos,q[14],z,u,true);arc<<k<<','<<q[14]<<','<<s.p<<','<<s.norm<<','<<locus::gap(s.x[0],s.x[2])<<','<<s.Z[0]/s.Z[2]<<','<<locus::curvature(eos,q[14],s.p,s.x[0])[0]<<','<<locus::curvature(eos,q[14],s.p,s.x[2],true)[0]<<','<<locus::curvature(eos,q[14],s.p,s.x[1])[0]<<','<<tau[14]<<','<<ds<<std::endl;q1=q2;q2=q;if(k%20==0)std::cout<<"arc "<<k<<" T="<<q[14]<<" gap="<<locus::gap(s.x[0],s.x[2])<<std::endl;if(ds<.02)ds=std::min(.02,ds*1.2);}
// Re-locate oil curvature zero from an independent 25 MPa LL anchor.
std::ofstream checks(out/"spinodal_crosscheck.csv");checks<<std::setprecision(17)<<"T_K,P_spinodal_MPa,lambda,lambda_half,closure,oil_vapor_parent_composition_gap,status\n";
for(double ts:{tc,593.,603.6,613.2}){auto a=refine::decode(f.front());double ph=25;if(!locus::correct(eos,ts,z,a,false,ph))throw std::runtime_error("spin anchor failure");auto ah=locus::eval(eos,ts,z,a,false,ph);double lh=locus::curvature(eos,ts,ph,ah.x[0])[0];bool found=false;for(double pl=24.8;pl>=7;pl-=.2){auto b=a;if(!locus::correct(eos,ts,z,b,false,pl))break;auto sl=locus::eval(eos,ts,z,b,false,pl);double ll=locus::curvature(eos,ts,pl,sl.x[0])[0];if(lh>0&&ll<0){for(int j=0;j<26;++j){double pm=(ph+pl)*.5;auto u=a;if(!locus::correct(eos,ts,z,u,false,pm))throw std::runtime_error("spin refinement failed");auto sm=locus::eval(eos,ts,z,u,false,pm);if(locus::curvature(eos,ts,pm,sm.x[0])[0]>0){ph=pm;a=u;}else{pl=pm;b=u;}}double ps=(pl+ph)*.5;auto u=a;locus::correct(eos,ts,z,u,false,ps);auto ss=locus::eval(eos,ts,z,u,false,ps);checks<<ts<<','<<ps<<','<<locus::curvature(eos,ts,ps,ss.x[0])[0]<<','<<locus::curvature(eos,ts,ps,ss.x[0],false,5e-6)[0]<<','<<ss.norm<<','<<(ts==tc?locus::gap(ss.x[0],sc.x[0]):std::numeric_limits<double>::quiet_NaN())<<",CURVATURE_ZERO\n";found=true;break;}ph=pl;a=b;lh=ll;}if(!found)checks<<ts<<",nan,nan,nan,nan,nan,NO_CERTIFIED_ZERO\n";}
// Independent same-temperature reverse and half-step path agreement, plus
// full production flash at both sides of selected low-T onset states.
MPMC::ThreePhaseFlashOptions opt;opt.waterComponent=0;opt.maximumIterations=240;opt.maximumStabilityIterations=160;opt.cpaSelectGibbsMinimumRoot=true;Flash flash(eos,opt);std::ofstream global(out/"side_global.csv");global<<std::setprecision(17)<<"T_K,P_MPa,offset_MPa,converged,phase_code,beta_gas,closure,missing_phase_stable,minimum_active_curvature\n";for(double t:{583.,586.,588.,589.,589.1,590.,593.}){auto u=refine::decode(f.front());if(!locus::correct(eos,t,z,u,true))continue;double pb=std::exp(u[13]);for(double off:{-.02,.02}){double p=pb+off;auto r=flash.flash(p*1e6,t,z);bool stable=false;double mincurv=std::numeric_limits<double>::quiet_NaN();if(r.converged){auto st=flash.stabilityTest(p*1e6,t,z,r.presence,r.composition);stable=st.valid&&st.stable;mincurv=1e100;for(int k=0;k<3;++k)if(r.presence.contains(static_cast<MPMC::CompositionalPhase>(k)))mincurv=std::min(mincurv,locus::curvature(eos,t,p,r.composition[k],k==1)[0]);}global<<t<<','<<p<<','<<off<<','<<r.converged<<','<<(r.converged?r.presence.bits():0)<<','<<r.phaseMoleFraction[1]<<','<<(r.converged?maxMaterialClosure(z,r):std::numeric_limits<double>::quiet_NaN())<<','<<stable<<','<<mincurv<<std::endl;}}return 0;}catch(const std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
